// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hash_string
IntegerVector hash_string(CharacterVector x);
RcppExport SEXP textreuse_hash_string(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    __result = Rcpp::wrap(hash_string(x));
    return __result;
END_RCPP
}
// shingle_ngrams
CharacterVector shingle_ngrams(CharacterVector words, int n);
RcppExport SEXP textreuse_shingle_ngrams(SEXP wordsSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type words(wordsSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(shingle_ngrams(words, n));
    return __result;
END_RCPP
}
