#' Candidate pairs
#'
#' Converts a comparison matrix generated by \code{\link{pairwise_cf}} into a
#' data frame of candidates for matches.
#'
#' @param m A matrix from \code{\link{pairwise_cf}}.
#' @return A data frame containing all the non-\code{NA} values from \code{m}.
#'   Columns \code{a} and \code{b} are the IDs from the original corpus as
#'   passed to the comparison function. Column \code{score} is the score
#'   returned by the comparison function.
#' @examples
#' dir <- system.file("extdata", package = "textreuse")
#' corpus <- TextReuseCorpus(dir = dir)
#' names(corpus) <- filenames(names(corpus))
#' m <- pairwise_cf(corpus, ratio_of_matches, directional = TRUE)
#' candidate_pairs(m)
#' @export
candidate_pairs <- function(m) {
  assert_that(is.matrix(m))
  matches <- which(!is.na(m))
  indexes <- arrayInd(matches, dim(m))
  score <- m[matches]
  a <- rownames(m)[indexes[ , 1]]
  b <- colnames(m)[indexes[ , 2]]
  df <- data.frame(a = a, b = b, score = score, stringsAsFactors = FALSE)
  class(df) <- c("tbl_df", "tbl", "data.frame")
  df
}
