#' Calculate minhash values
#'
#' A minhash value is calculated by hashing a string to an integer and selecting
#' the minimum value. Repeated minhash values are generated by using different
#' hash functions: these different hash functions are created by using
#' performing a bitwise \code{XOR} operation (\code{\link{bitwXor}}) with a
#' vector of random integers. It is vital that you use the same random integers
#' for every document in your corpus. To generate these, see
#' \code{\link{random_ints}}.
#'
#' @param x The vector to be minhashed.
#' @param random A vector of integers.
#' @return An integer vector with the same length as \code{random}.
#' @seealso \code{\link{random_ints}}
#' @examples
#' set.seed(253)
#' r <- random_ints(3)
#' minhash(c("Some", "words", "are", "the", "same"), r)
#' minhash(c("Some", "words", "are", "different", "though"), r)
#' @export
minhash <- function(x, random) UseMethod("minhash")

#' @export
minhash.character <- function(x, random) {
  assert_that(is.integer(random))
  h <- hash_string(x)
  vapply(random, function(i) { min(bitwXor(h, i)) },
         integer(1), USE.NAMES = FALSE)
}

#' Generate random integers for minhashing
#'
#' It is crucial that you use the same random integers for every document in the
#' corpus. The random integers generated by this function are intended to be
#' passed to \code{\link{minhash}}.
#' @param n The number of random integers to generate.
#' @return A vector of integers
#' @seealso \code{\link{minhash}}
#' @examples
#' random_ints(3)
#' @export
random_ints <- function(n) {
  as.integer(runif(n, -2147483648, 2147483647))
}
