# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Hash a string to an integer
#' @param x A character vector to be hashed.
#' @return A vector of integer hashes.
#' @examples
#' s <- c("How", "many", "roads", "must", "a", "man", "walk", "down")
#' hash_string(s)
#' @export
hash_string <- function(x) {
    .Call('textreuse_hash_string', PACKAGE = 'textreuse', x)
}

shingle_ngrams <- function(words, n) {
    .Call('textreuse_shingle_ngrams', PACKAGE = 'textreuse', words, n)
}

skip_ngrams <- function(words, n, k) {
    .Call('textreuse_skip_ngrams', PACKAGE = 'textreuse', words, n, k)
}

sw_matrix <- function(m, a, b, match, mismatch, gap, progress) {
    .Call('textreuse_sw_matrix', PACKAGE = 'textreuse', m, a, b, match, mismatch, gap, progress)
}

